# Generated by Django 2.2.4 on 2019-12-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BajajScienceCentre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('caption', models.CharField(max_length=200)),
            ],
        ),
    ]
