# Generated by Django 2.2.4 on 2020-08-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BajajScienceCentre', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
