# Generated by Django 2.2.4 on 2020-09-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BajajScienceCentre', '0003_auto_20200821_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitingFactulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('image_source', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
