# Generated by Django 2.2.4 on 2020-09-30 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BajajScienceCentre', '0004_visitingfactulty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisitingFactulty',
            new_name='VisitingFaculty',
        ),
    ]
