# Generated by Django 2.2.4 on 2020-09-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BajajScienceCentre', '0005_auto_20200930_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitingfaculty',
            name='image_source',
            field=models.FileField(max_length=1000, null=True, upload_to=''),
        ),
    ]
